### ISSUE TITLE
Negative value for vsk.Param() causes error

### ISSUE THREAD

**Issue by LoicGoulefert** [abey79/vsketch#93]
Minimal code to reproduce:

```
class SimpleSketch(vsketch.Vsketch):
    # Sketch parameters:
    a = vsketch.Param(-1.4)

    def draw(self) -> None:
        self.size("21cmx28.2cm", landscape=False)
        self.scale("cm")

    def finalize(self) -> None:
        self.vpype("linemerge linesimplify reloop linesort")

if __name__ == "__main__":
    vsk = AttractorsSketch()
    vsk.draw()
    vsk.finalize()
    vsk.display()
```

The error when running `vsk run simple`:

```
Traceback (most recent call last):
  File "/home/loic/.cache/pypoetry/virtualenvs/vsketch-Rpwrotvj-py3.7/bin/vsk", line 5, in <module>
    cli()
  File "/home/loic/.cache/pypoetry/virtualenvs/vsketch-Rpwrotvj-py3.7/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/loic/.cache/pypoetry/virtualenvs/vsketch-Rpwrotvj-py3.7/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/loic/.cache/pypoetry/virtualenvs/vsketch-Rpwrotvj-py3.7/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/loic/.cache/pypoetry/virtualenvs/vsketch-Rpwrotvj-py3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/loic/.cache/pypoetry/virtualenvs/vsketch-Rpwrotvj-py3.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/loic/.cache/pypoetry/virtualenvs/vsketch-Rpwrotvj-py3.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/loic/.cache/pypoetry/virtualenvs/vsketch-Rpwrotvj-py3.7/lib/python3.7/site-packages/typer/main.py", line 497, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/loic/Documents/python/vsketch/vsketch_cli/cli.py", line 204, in run
    show(str(path), second_screen=fullscreen)
  File "/home/loic/Documents/python/vsketch/vsketch_cli/gui.py", line 23, in show
    widget = SketchViewer(pathlib.Path(path))
  File "/home/loic/Documents/python/vsketch/vsketch_cli/sketch_viewer.py", line 98, in __init__
    self.reload_sketch_class()
  File "/home/loic/Documents/python/vsketch/vsketch_cli/sketch_viewer.py", line 162, in reload_sketch_class
    self._sidebar.params_widget.set_params(self._sketch_class.get_params())
  File "/home/loic/Documents/python/vsketch/vsketch_cli/param_widget.py", line 175, in set_params
    widget = FloatParamWidget(param)
  File "/home/loic/Documents/python/vsketch/vsketch_cli/param_widget.py", line 80, in __init__
    decimals = max(1, 1 - math.floor(math.log10(val)))
ValueError: math domain error
```

EDIT:

- `a = vsk.Param(-1)` works fine,
- `a = vsk.Param(-1.4)` causes the error
- `a = vsk.Param(-1.4, decimals=1)` works fine

So maybe we need a way to check if the value input has decimals, and change `FloatParamWidget`'s `__init__` function to detect that.

**Comment by abey79** [comment]
Fixed by #189
